{% set name = "e3sm-tools" %}
{% set version = "3.0.0rc2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../..
  patches:
    - 0001-fix-boz-erros-in-interpinic-build.patch
    - 0002-fix-iargc-issue-in-interpinic-build.patch
    - 0003-fix-boz-erros-in-mksurfdata_map-build.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
  host:
    - hdf5
    - hdf5 * nompi_*
    - libcurl
    - libnetcdf
    - libnetcdf * nompi_*
    - libpng
    - netcdf-fortran
    - netcdf-fortran * nompi_*

test:
  requires:
    - curl
    - nccmp
  commands:
    - curl -O https://web.lcrc.anl.gov/public/e3sm/inputdata/cpl/gridmaps/IcoswISC30E3r5/map_IcoswISC30E3r5_to_r05_traave.20231121.nc
    - curl -O https://web.lcrc.anl.gov/public/e3sm/inputdata/share/domains/domain.ocn.IcoswISC30E3r5.231121.nc
    - curl -O https://web.lcrc.anl.gov/public/e3sm/inputdata/share/domains/domain.lnd.r05_IcoswISC30E3r5.231121.nc
    - curl -O https://web.lcrc.anl.gov/public/e3sm/inputdata/share/domains/domain.ocn.r05_IcoswISC30E3r5.231121.nc
    - gen_domain -o IcoswISC30E3r5 -l r05 -m map_IcoswISC30E3r5_to_r05_traave.20231121.nc
    - nccmp -d --Tolerance=1e-5 domain.ocn.IcoswISC30E3r5.*.nc
    - nccmp -d --Tolerance=1e-5 domain.lnd.r05_IcoswISC30E3r5.*.nc
    - nccmp -d --Tolerance=1e-5 domain.ocn.r05_IcoswISC30E3r5.*.nc
    - test -f "${PREFIX}/bin/cube_to_target"
    - test -f "${PREFIX}/bin/interpinic"
    - test -f "${PREFIX}/bin/mksurfdata_map"
    - test -f "${PREFIX}/bin/squadgen"

about:
  home: https://github.com/xylar/e3sm-tools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tools needed to integrate new meshes into the Energy Exascale Earth System Model
  doc_url: https://github.com/xylar/e3sm-tools
  dev_url: https://github.com/xylar/e3sm-tools

extra:
  recipe-maintainers:
    - xylar