{% set name = "e3sm-tools" %}
{% set version = "3.0.0" %}
{% set e3sm_version = "3.0.0" %}
{% set cime_version = "cime6.0.234" %}
{% set squadgen_hash = "e39223e31a7b57adc1e5b946bd11dcfbaf52e76e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - path: ../..

  - url: https://github.com/E3SM-Project/E3SM/archive/refs/tags/v{{ e3sm_version }}.tar.gz
    sha256: 5fae4c5c5e30099fae7500cf32cd77998e51bcda20ac4f170b3ad59dc44bb25c
    folder: submodules/E3SM
    patches:
      - 0001-fix-boz-erros-in-interpinic-build.patch
      - 0002-fix-iargc-issue-in-interpinic-build.patch
      - 0003-fix-boz-erros-in-mksurfdata_map-build.patch

  - url: https://github.com/ESMCI/cime/archive/refs/tags/{{ cime_version }}.tar.gz
    sha256: 9596339ac0dcec4d2b2817d526ea8eabc27bdfcd6903bd58a14add21f2f1afcd
    folder: submodules/cime

  - url: https://github.com/ClimateGlobalChange/squadgen/archive/{{ squadgen_hash }}.tar.gz
    sha256: 5c983255222534848916213776c6569415edac140232f2833f11529d029af6d5
    folder: submodules/squadgen

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
  host:
    - hdf5
    - hdf5 * nompi_*
    - libcurl
    - libnetcdf
    - libnetcdf * nompi_*
    - libpng
    - netcdf-fortran
    - netcdf-fortran * nompi_*

test:
  requires:
    - curl
    - nccmp
  commands:
    - curl -O https://web.lcrc.anl.gov/public/e3sm/inputdata/cpl/gridmaps/IcoswISC30E3r5/map_IcoswISC30E3r5_to_ne30pg2_traave.20231121.nc
    - curl -O https://web.lcrc.anl.gov/public/e3sm/inputdata/share/domains/domain.ocn.IcoswISC30E3r5.231121.nc
    - curl -O https://web.lcrc.anl.gov/public/e3sm/inputdata/share/domains/domain.lnd.ne30pg2_IcoswISC30E3r5.231121.nc
    - curl -O https://web.lcrc.anl.gov/public/e3sm/inputdata/share/domains/domain.ocn.ne30pg2_IcoswISC30E3r5.231121.nc
    - gen_domain -o IcoswISC30E3r5 -l ne30pg2 -m map_IcoswISC30E3r5_to_ne30pg2_traave.20231121.nc
    - nccmp -d -T 0.0 domain.ocn.IcoswISC30E3r5.*.nc
    - nccmp -d -T 0.0 domain.lnd.ne30pg2_IcoswISC30E3r5.*.nc
    - nccmp -d -T 0.0 domain.ocn.ne30pg2_IcoswISC30E3r5.*.nc
    - test -f "${PREFIX}/bin/cube_to_target"
    - test -f "${PREFIX}/bin/interpinic"
    - test -f "${PREFIX}/bin/mksurfdata_map"
    - test -f "${PREFIX}/bin/squadgen"

about:
  home: https://github.com/xylar/e3sm-tools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tools needed to integrate new meshes into the Energy Exascale Earth System Model
  doc_url: https://github.com/xylar/e3sm-tools
  dev_url: https://github.com/xylar/e3sm-tools

extra:
  recipe-maintainers:
    - xylar
