#!/usr/bin/env python
import argparse

import pandas


def cdscan_replacement():
    parser = argparse.ArgumentParser(
                    prog='cdscan_replacement',
                    description='create an XML file with the list of input '
                                'files')
    parser.add_argument('output_file',
                        help='the XML file to write')
    parser.add_argument('input_files', nargs='+',
                        help='a single file containing a list of files or '
                             'multiple input files to include')
    args = parser.parse_args()

    output_file = args.output_file
    input_files = args.input_files
    if len(input_files) == 1:
        files = []
        # Convert text file of files to a list of files.
        with open(input_files[0]) as f:
            for line in f:
                files.append(line.strip())
        input_files = files
    dataframe = pandas.read_table(input_files)
    dataframe.to_xml(output_file)


if __name__ == '__main__':
    cdscan_replacement()
